import { StyleSheet, Dimensions } from 'react-native';

const styles = StyleSheet.create({
    container: {
      paddingTop: 60,
      flex: 1,
      backgroundColor: '#fff',
      justifyContent: 'center',
    },
    title: {
      marginTop: 5,
      marginBottom: 10,
      marginHorizontal: 20,
      color: '#000',
      fontWeight: 'bold',
      fontSize: 26,
      lineHeight: 32,
    },
    optionContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginBottom: 20,
      marginHorizontal: 90,
    },
    optionButton: {
      paddingVertical: 10,
      paddingHorizontal: 50,
      borderRadius: 20,
      backgroundColor: '#c9c9c9',
    },
    selectedOption: {
      backgroundColor: '#000',
      zIndex: 999,
    },
    optionText: {
      color: '#fff',
    },
    headerContainer: {
      paddingHorizontal: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    title2: {
      color: '#000',
      fontWeight: 'bold',
      fontSize: 24,
      lineHeight: 32,
    },
    dropdown: {
      width: 150,
      height: 40,
      borderRadius: 5,
      paddingHorizontal: 10,
      justifyContent: 'center',
    },
    placeholderStyle: {
      color: '#9B9B9B',
    },
    labelStyle: {
      color: '#9B9B9B',
      fontSize: 14,
      textAlign: 'right',
    },
    titleTransfers: {
      marginBottom: 10,
      color: '#000',
      fontWeight: 'bold',
      fontSize: 24,
      lineHeight: 32,
    },
    transfers: {
      padding: 20,
    },
    transferCard: {
      backgroundColor: '#EEEEEE',
      borderRadius: 17,
      padding: 15,
      marginVertical: 10,
    },
    transferContent: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    transferInfo: {
      flex: 1,
    },
    transferTitle: {
      fontSize: 16,
      marginTop: 7,
      marginBottom: 7,
    },
    transferText: {
      opacity: 0.6,
    },
    transferDate: {
      opacity: 0.5,
    },
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
      width: '90%',
      height: '60%',
      backgroundColor: '#F5F5F5',
      borderRadius: 10,
      padding: 20,
      alignItems: 'center',
      elevation: 10,
    },
    field: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: '100%',
      marginVertical: 10,
      alignItems: 'center',
      borderColor: '#ccc',
      paddingVertical: 10,
      borderBottomWidth: 2,
    },
    label: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#5D5D5D',
      opacity: 0.5,
    },
    value: {
      fontSize: 16,
      color: '#000',
      opacity: 0.7,
    },
    category: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    categoryText: {
      marginRight: 5,
      fontSize: 16,
      color: '#000',
      opacity: 0.7,
    },
    categoryIcon: {
      fontSize: 16,
    },
    editButton: {
      marginTop: 'auto',
      width: '100%',
      backgroundColor: '#fff',
      borderRadius: 10,
      paddingVertical: 15,
      borderWidth: 2,
      borderColor: '#000',
      alignItems: 'center',
    },
    editButtonText: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#000',
    },
    closeButton: {
      marginTop: 10,
      width: '100%',
      backgroundColor: '#333',
      borderRadius: 10,
      paddingVertical: 15,
      alignItems: 'center',
    },
    closeButtonText: {
      fontSize: 16,
      color: '#fff',
    },
    dataText: {
      textAlign: 'center',
      marginTop: 20,
      color: '#666',
    },
    pieChartContainer: {
      alignItems: 'center',
      marginVertical: 5,
    },
    chartContainer: {
      paddingHorizontal: 20,
      alignItems: 'center',
      position: 'relative',
    },
    tooltip: {
      position: 'absolute',
      top: 10,
      left: 10,
      backgroundColor: '#2F1155',
      color: '#fff',
      padding: 5,
      borderRadius: 5,
      zIndex: 10,
    },
    optionText: {
      color: '#fff',
    },
    monthSelectorContainer: {
      paddingHorizontal: 20,
      marginTop: 20,
      alignItems: 'center',
      backgroundColor: '#F5F5F5',
      borderRadius: 10,
      paddingVertical: 10,
    },
    monthScrollView: {
      alignItems: 'center',
    },
    monthButton: {
      width: 80,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 10,
      marginHorizontal: 5,
    },
    selectedMonthButton: {
      backgroundColor: '#B0B0B0',
      borderRadius: 10,
      paddingVertical: 15,
    },
    monthText: {
      color: '#666666',
      fontWeight: 'normal',
      fontSize: 16,
    },
    selectedMonthText: {
      color: '#333333',
      fontWeight: '600',
      fontSize: 18,
    },
    notifications: {
      marginTop: 10,
      padding: 20,
    },
    notificationsCard: {
      backgroundColor: '#EEEEEE',
      borderRadius: 17,
      padding: 15,
      marginBottom: 15,
    },
    notificationsContent: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    notificationInfo: {
      flex: 1,
    },
    notificationTitle: {
      fontSize: 16,
      marginTop: 7,
      marginBottom: 7,
    },
    notificationText: {
      opacity: 0.6,
    },
    notificationDate: {
      opacity: 0.5,
    },
    notificationIcon: {
      marginLeft: 10,
    },
    selectIcon: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    userImageContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    userImageSettings: {
      width: 200,
      height: 200,
      marginHorizontal: 'auto',
    },
    nameUserSettings: {
      textAlign: 'center',
      fontSize: 28,
      marginTop: 26,
      fontWeight: '700',
      letterSpacing: 1.2,
      color: '#666666',
    },
    arrowButtonIcon: {
      padding: 10,
    },
    arrowIcon: {
      fontSize: 40,
      color: '#000',
    },
    button: {
      borderRadius: 15,
      backgroundColor: '#fff',
      padding: 20,
      marginTop: 'auto',
      marginHorizontal: 'auto',
      width: '80%',
      marginBottom: 20,
      borderWidth: 1,
      borderBottomWidth: 4,
      borderRightWidth: 4,
      borderBottomColor: '#000',
      borderRightColor: '#000',
    },
    buttonText: {
      color: '#000',
      textAlign: 'center',
      fontSize: 16,
      fontWeight: 'bold',
    },
    header: {
      flexDirection: 'row',
      paddingHorizontal: 25,
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    titleApp: {
      color: '#000',
      fontWeight: 'bold',
      fontSize: 32,
      lineHeight: 32,
      fontStyle: 'italic',
      fontFamily: 'serif',
    },
    username: {
      color: '#000',
      fontSize: 18,
      fontWeight: '400',
      opacity: 0.5,
    },
    userImage: {
      width: 50,
      height: 50,
    },
    balanceContainer: {
      marginVertical: 20,
      paddingHorizontal: 20,
    },
    balance: {
      backgroundColor: '#000',
      borderRadius: 30,
      paddingHorizontal: 40,
      paddingVertical: 35,
      borderRadius: 15,
    },
    balanceTitle: {
      color: '#fff',
      fontSize: 20,
      fontWeight: '600',
      opacity: 0.7,
      fontFamily: 'monospace',
    },
    balanceText: {
      color: '#fff',
      fontSize: 34,
      fontWeight: 'bold',
    },
    operations: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      marginVertical: 10,
    },
    operation: {
      width: 100,
      height: 95,
      backgroundColor: '#fff',
      marginHorizontal: 10,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 16,
      borderWidth: 1,
      borderBottomWidth: 8,
      borderRightWidth: 8,
      borderBottomColor: '#000',
      borderRightColor: '#000',
    },
    btn: {
      marginBottom: 5,
    },
  descOperation: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '400',
    color: '#000',
    opacity: 0.4,
  },
  cardsHome: {
    paddingHorizontal: 20,
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardHomeContainer: {
    width: 170,
    height: 150,
    borderRadius: 15,
    padding: 15,
    backgroundColor: '#ededed',
    alignItems: 'flex-start',
  },
  cardTotal: {
    color: '#000',
    fontSize: 24,
    fontWeight: 'bold',
    marginTop: 'auto',
  },
  cardCategory: {
    color: '#000',
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'monospace',
    opacity: 0.6,
  },
  goalsTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
  },
  goals: {
    paddingVertical: 15,
    paddingHorizontal: 30,
  },
  goal: {
    backgroundColor: '#fff',
    padding: 15,
    marginBottom: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomColor: '#000',
    borderRightColor: '#000',
  },
  goalTitle: {
    marginTop: 8,
    marginBottom: 16,
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
    opacity: 0.8,
  },
  goalRemainingValue: {
    fontSize: 16,
    marginLeft: 'auto',
    fontWeight: '500',
    color: '#000',
    opacity: 0.7,
  },
  goalBarProgress: {
    marginTop: 10,
    borderWidth: 0,
    borderColor: '#000',
    width: '100%',
  },
  addGoalCard: {
    marginVertical: 15,
    padding: 14,
    borderRadius: 10,
    backgroundColor: '#ededed',
  },
  addGoalContent: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addGoalIcon: {
    marginRight: 5,
  },
  addGoalText: {
    fontSize: 16,
    color: '#000',
    fontWeight: '500',
  },
  headerTransfer: {
    flexDirection: 'row',
    paddingHorizontal: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputs: {
    marginTop: '15%',
    marginBottom: '5%',
    width: '100%',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: 'gray',
    borderRadius: 15,
    paddingHorizontal: 10,
    backgroundColor: '#F2F2F2',
    width: '100%',
    marginBottom: 10,
  },
  input: {
    flex: 1,
    paddingVertical: 20,
    paddingHorizontal: 20,
    backgroundColor: '#F2F2F2',
    borderRadius: 15,
    fontSize: 16,
  },
  picker: {
    flex: 1,
    backgroundColor: '#F2F2F2',
    borderRadius: 15,
  },
  valueTransfer: {
    textAlign: 'center',
    color: '#000',
    fontWeight: 'bold',
    fontSize: 32,
    lineHeight: 32,
  },
  main: {
    paddingHorizontal: 20,
  },
  keyboard: {
    width: 340,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  key: {
    width: '20%',
    margin: '5%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  keyText: {
    fontSize: 24,
    color: '#333',
  },
  dataText: {
    textAlign: 'center',
    marginTop: 20,
    color: '#666',
  },
});

export default styles;
